"""empty message

Revision ID: 534a52cf200a
Revises: 752c6d630ab7
Create Date: 2022-07-05 12:29:43.435760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534a52cf200a'
down_revision = '752c6d630ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_product_unique', 'product_user', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_unique', 'product_user', type_='unique')
    # ### end Alembic commands ###
