"""empty message

Revision ID: 752c6d630ab7
Revises: 9f59f3ece5c9
Create Date: 2022-07-05 12:23:10.690477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752c6d630ab7'
down_revision = '9f59f3ece5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_user')
    # ### end Alembic commands ###
